alias: AGS Service Automation
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.ags_media_system
    attribute: active_speakers
  - platform: state
    entity_id:
      - media_player.ags_media_system
    attribute: ags_status
condition: []
action:
  - if:
      - condition: not
        conditions:
          - condition: state
            entity_id: media_player.ags_media_system
            state: "[]"
            attribute: active_speakers
          - condition: state
            entity_id: media_player.ags_media_system
            state: "off"
            attribute: ags_status
          - condition: state
            entity_id: media_player.ags_media_system
            state: none
            attribute: primary_speaker
          - condition: state
            entity_id: media_player.ags_media_system
            state: Not available
            attribute: active_speakers
          - condition: state
            entity_id: media_player.ags_media_system
            state: Not available
            attribute: ags_status
          - condition: state
            entity_id: media_player.ags_media_system
            state: Not available
            attribute: primary_speaker
    then:
      - service: media_player.join
        data:
          entity_id: "{{ states.media_player.ags_media_system.attributes.primary_speaker}}"
          group_members: >-
            {{ states.media_player.ags_media_system.attributes.active_speakers
            }}
    else: null
    alias: Join Action
  - if:
      - condition: not
        conditions:
          - condition: state
            entity_id: media_player.ags_media_system
            state: "[]"
            attribute: inactive_speakers
          - condition: state
            entity_id: media_player.ags_media_system
            state: Not available
            attribute: inactive_speakers
    then:
      - service: media_player.unjoin
        data: {}
        target:
          entity_id: >-
            {{
            states.media_player.ags_media_system.attributes.inactive_speakers}}
      - service: media_player.media_pause
        data: {}
        target:
          entity_id: >-
            {{
            states.media_player.ags_media_system.attributes.inactive_speakers}}
      - service: media_player.clear_playlist
        data: {}
        target:
          entity_id: >-
            {{
            states.media_player.ags_media_system.attributes.inactive_speakers}}
    else: null
    alias: Remove Action
    enabled: true
  - if:
      - condition: not
        conditions:
          - condition: state
            entity_id: media_player.ags_media_system
            state: "[]"
            attribute: ags_inactive_tv_speakers
          - condition: state
            entity_id: media_player.ags_media_system
            state: Not available
            attribute: ags_inactive_tv_speakers
    then:
      - service: media_player.select_source
        data:
          source: TV
        target:
          entity_id: >-
            {{
            states.media_player.ags_media_system.attributes.ags_inactive_tv_speakers}}
    alias: Reset TV Speakers to TV after
mode: single
